### ISSUE TITLE
problem with compiling release apk on android

### ISSUE THREAD

**Issue by sindycarlo** [AgNO3/jcifs-ng#107]
i have a problem when i compile apk on release with android studio.

Warning: jcifs.smb.Kerb5Authenticator: can't find referenced class org.ietf.jgss.GSSCredential
Warning: jcifs.smb.Kerb5Authenticator: can't find referenced class org.ietf.jgss.GSSContext
Warning: jcifs.smb.Kerb5Authenticator: can't find referenced class org.ietf.jgss.GSSException
Warning: jcifs.smb.Kerb5Authenticator: can't find referenced class org.ietf.jgss.GSSException
Warning: jcifs.smb.Kerb5Authenticator: can't find referenced class org.ietf.jgss.GSSException
Warning: jcifs.smb.Kerb5Context: can't find referenced class org.ietf.jgss.GSSManager
Warning: jcifs.smb.Kerb5Context: can't find referenced class org.ietf.jgss.GSSManager
Warning: jcifs.smb.Kerb5Context: can't find referenced class org.ietf.jgss.GSSName
Warning: jcifs.smb.Kerb5Context: can't find referenced class org.ietf.jgss.GSSName
Warning: jcifs.smb.Kerb5Context: can't find referenced class org.ietf.jgss.GSSCredential
Warning: jcifs.smb.Kerb5Context: can't find referenced class org.ietf.jgss.GSSManager
Warning: jcifs.smb.Kerb5Context: can't find referenced class org.ietf.jgss.GSSManager
Warning: jcifs.smb.Kerb5Context: can't find referenced class org.ietf.jgss.GSSContext
Warning: jcifs.smb.Kerb5Context: can't find referenced class org.ietf.jgss.GSSContext
Warning: jcifs.smb.Kerb5Context: can't find referenced class org.ietf.jgss.GSSContext
Warning: jcifs.smb.Kerb5Context: can't find referenced class org.ietf.jgss.GSSContext
Warning: jcifs.smb.Kerb5Context: can't find referenced class org.ietf.jgss.GSSContext
Warning: jcifs.smb.Kerb5Context: can't find referenced class org.ietf.jgss.GSSContext
Warning: jcifs.smb.Kerb5Context: can't find referenced class org.ietf.jgss.GSSContext
Warning: jcifs.smb.Kerb5Context: can't find referenced class org.ietf.jgss.GSSContext
Warning: jcifs.smb.Kerb5Context: can't find referenced class org.ietf.jgss.GSSContext
Warning: jcifs.smb.Kerb5Context: can't find referenced class org.ietf.jgss.GSSContext
Warning: jcifs.smb.Kerb5Context: can't find referenced class org.ietf.jgss.GSSContext
Warning: jcifs.smb.Kerb5Context: can't find referenced class org.ietf.jgss.GSSContext
Warning: jcifs.smb.Kerb5Context: can't find referenced class org.ietf.jgss.GSSContext
Warning: jcifs.smb.Kerb5Context: can't find referenced class org.ietf.jgss.GSSContext
Warning: jcifs.smb.Kerb5Context: can't find referenced class org.ietf.jgss.GSSContext
Warning: jcifs.smb.Kerb5Context: can't find referenced class org.ietf.jgss.MessageProp
Warning: jcifs.smb.Kerb5Context: can't find referenced class org.ietf.jgss.MessageProp
Warning: jcifs.smb.Kerb5Context: can't find referenced class org.ietf.jgss.GSSContext
Warning: jcifs.smb.Kerb5Context: can't find referenced class org.ietf.jgss.GSSException
Warning: jcifs.smb.Kerb5Context: can't find referenced class org.ietf.jgss.GSSContext
Warning: jcifs.smb.Kerb5Context: can't find referenced class org.ietf.jgss.GSSContext
Warning: jcifs.smb.Kerb5Context: can't find referenced class org.ietf.jgss.GSSContext
Warning: jcifs.smb.Kerb5Context: can't find referenced class org.ietf.jgss.GSSName
Warning: jcifs.smb.Kerb5Context: can't find referenced class org.ietf.jgss.GSSContext
Warning: jcifs.smb.Kerb5Context: can't find referenced class org.ietf.jgss.GSSContext
Warning: jcifs.smb.Kerb5Context: can't find referenced class org.ietf.jgss.Oid
Warning: jcifs.smb.Kerb5Context: can't find referenced class org.ietf.jgss.GSSContext
Warning: jcifs.smb.Kerb5Context: can't find referenced class org.ietf.jgss.Oid
Warning: jcifs.smb.Kerb5Context: can't find referenced class org.ietf.jgss.Oid
Warning: jcifs.smb.Kerb5Context: can't find referenced class org.ietf.jgss.GSSManager
Warning: jcifs.smb.Kerb5Context: can't find referenced class org.ietf.jgss.GSSCredential
Warning: jcifs.smb.Kerb5Context: can't find referenced class org.ietf.jgss.Oid
Warning: jcifs.smb.Kerb5Context: can't find referenced class org.ietf.jgss.GSSException
Warning: jcifs.smb.Kerb5Context: can't find referenced class org.ietf.jgss.GSSManager
Warning: jcifs.smb.Kerb5Context: can't find referenced class org.ietf.jgss.GSSName
Warning: jcifs.smb.Kerb5Context: can't find referenced class org.ietf.jgss.GSSContext
Warning: jcifs.smb.Kerb5Context: can't find referenced class org.ietf.jgss.Oid
Warning: jcifs.smb.Kerb5Context: can't find referenced class org.ietf.jgss.Oid
Warning: jcifs.smb.Kerb5Context: can't find referenced class org.ietf.jgss.GSSContext
Warning: jcifs.smb.Kerb5Context: can't find referenced class org.ietf.jgss.GSSName
Warning: jcifs.smb.Kerb5Context: can't find referenced class org.ietf.jgss.GSSName
Warning: jcifs.smb.Kerb5Context: can't find referenced class org.ietf.jgss.GSSManager
Warning: jcifs.smb.Kerb5Context: can't find referenced class org.ietf.jgss.GSSCredential
Warning: jcifs.smb.Kerb5Context: can't find referenced class org.ietf.jgss.Oid
Warning: jcifs.smb.Kerb5Context: can't find referenced class org.ietf.jgss.GSSException
Warning: jcifs.smb.Kerb5Context: can't find referenced class org.ietf.jgss.GSSException
Warning: jcifs.smb.Kerb5Context: can't find referenced class org.ietf.jgss.GSSException
Warning: jcifs.smb.Kerb5Context: can't find referenced class org.ietf.jgss.GSSException
Warning: jcifs.smb.Kerb5Context: can't find referenced class org.ietf.jgss.GSSException
Warning: jcifs.smb.Kerb5Context: can't find referenced class org.ietf.jgss.Oid
Warning: jcifs.smb.Kerb5Context: can't find referenced class org.ietf.jgss.Oid

how can i resolve dependecies?

**Comment by sindycarlo** [comment]
i think the problem is in proguard-rules.txt, so i'v added -dontwarn org.ietf.** , and the problem is solved. but when i use the library with windows shared folder i notice this error:

 java.security.NoSuchAlgorithmException: MessageDigest MD4 implementation not found

**Comment by oleg30** [comment]
As I see, jcifs uses bouncycastle's MessageDigest, so you need to write -keep class org.bouncycastle.jcajce.** (or -keep class org.bouncycastle.**) in proguard-rules.txt (-dontwarn doesn't solve the problem, it just disable warning). I had such an  error and solved it like this.

**Comment by sindycarlo** [comment]
Thanks. Another questions, is it possible to calculate Md5 of a SmbResource?

**Comment by mbechler** [comment]
To add a bit of context: The org.ietf.jgss classes are for kerbereros authentication which Android does not support. They should be optional.

There are no special functions for calculating file hashes. 

As I take it that you also figured out the bouncycastle issue, I'm closing this. If not, feel free to reopen.

**Comment by avik1990** [comment]
@sindycarlo how did you solve.Can you share the solution a bit?
