### ISSUE TITLE
SmbException while browsing HP printer share

### ISSUE THREAD

**Issue by courville** [AgNO3/jcifs-ng#149]
This was not causing any issue with jcifs old implementation but I get an SmbException while doing ``smbcli 2 smb://HPF430B907181D/ "" GUEST ""``
```
jcifs.smb.SmbException: smb://HPF430B907181D/
	at jcifs.smb.SmbEnumerationUtil.doShareEnum(SmbEnumerationUtil.java:175)
	at jcifs.smb.SmbEnumerationUtil.doEnum(SmbEnumerationUtil.java:222)
	at jcifs.smb.SmbEnumerationUtil.listFiles(SmbEnumerationUtil.java:283)
	at jcifs.smb.SmbFile.listFiles(SmbFile.java:1192)
	at smbcli.main(smbcli.java:121)
Caused by: java.net.UnknownHostException: HPF430B907181D
	at jcifs.netbios.NameServiceClientImpl.getAllByName(NameServiceClientImpl.java:1025)
	at jcifs.netbios.NameServiceClientImpl.getAllByName(NameServiceClientImpl.java:54)
	at jcifs.smb.SmbTransportPoolImpl.getSmbTransport(SmbTransportPoolImpl.java:170)
	at jcifs.smb.SmbTransportPoolImpl.getSmbTransport(SmbTransportPoolImpl.java:47)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:560)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:484)
	at jcifs.smb.SmbEnumerationUtil.doShareEnum(SmbEnumerationUtil.java:149)
	... 4 more
Caught a CIFSException on listFiles
```
Pcap file is provided here: 
[hpprinter-smbexception-browsing.pcap.zip](https://github.com/AgNO3/jcifs-ng/files/2949627/hpprinter-smbexception-browsing.pcap.zip)
I am aligned with latest jcifs-ng-2.1.3-SNAPSHOT.jar.
Simple java test program is provided here: https://gist.github.com/courville/a0e6fe1ce2f31c9adc52191216eed3e0

**Comment by mbechler** [comment]
Is this a NetBIOS name or a DNS name. If NetBIOS, make sure that you have a correct jcifs.resolveOrder.
The packet capture does not contain either a DNS request nor a NetBIOS request for that name, are you sure that this is the correct capture.

**Comment by courville** [comment]
My mistake I used HPF430B907181D instead of HPF430B907191D (8->9) but I still have an
error.
To answer your question HPF430B907191D is a NetBIOS name (not DNS). I kept the jcifs.resolveOrder as default one.
I have performed again the capture with ``smbcli 2 smb://HPF430B907191D/ "" GUEST ""``.
The HP printer has address 192.168.0.150.
Here is the capture: [hpprinter-smbexception-browsing2.pcap.zip](https://github.com/AgNO3/jcifs-ng/files/2974614/hpprinter-smbexception-browsing2.pcap.zip)
And there the trace logs:
```
Enabling SMB2
smbFile is a server
2019-03-17 00:54:49 DEBUG SmbTransportPoolImpl:93 - New transport connection Transport0[HPF430B907191D<20>/192.168.0.150:445,state=0,signingEnforced=false,usage=1]
2019-03-17 00:54:49 DEBUG Transport:568 - Connecting Transport0
2019-03-17 00:54:49 DEBUG SmbTransportImpl:681 - Connecting in state 1 addr 192.168.0.150
2019-03-17 00:54:49 DEBUG SmbTransportImpl:705 - Negotiation response on Transport0 :jcifs.internal.SmbNegotiation@4d3db329
2019-03-17 00:54:49 DEBUG SmbComNegotiateResponse:259 - Signing not-enabled not-required
2019-03-17 00:54:49 DEBUG SmbComNegotiateResponse:295 - Unicode is enabled
2019-03-17 00:54:49 DEBUG SmbTransportImpl:715 - Signature negotiation enforced false (server false) enabled false (server false)
2019-03-17 00:54:49 DEBUG SmbTransportImpl:394 - Establishing new session SmbSession[credentials=GUEST,targetHost=hpf430b907191d,targetDomain=null,uid=0,connectionState=0,usage=1] on Transport0
2019-03-17 00:54:49 DEBUG SmbTreeImpl:587 - treeConnect: unc=\\hpf430b907191d\IPC$,service=?????
2019-03-17 00:54:49 DEBUG SmbSessionImpl:471 - sessionSetup: GUEST
2019-03-17 00:54:49 DEBUG SmbSessionImpl:843 - Performing legacy session setup
2019-03-17 00:54:49 DEBUG SmbTreeImpl:692 - Secure negotiation does not apply
2019-03-17 00:54:49 DEBUG SmbTreeConnection:142 - Switching tree
2019-03-17 00:54:49 DEBUG SmbTreeConnection:144 - Acquired tree on switch SmbTree[share=IPC$,service=IPC,tid=0,inDfs=false,inDomainDfs=false,connectionState=2,usage=2]
2019-03-17 00:54:49 DEBUG SmbResourceLocatorImpl:392 - Share is IPC IPC$
2019-03-17 00:54:49 DEBUG SmbTransportPoolImpl:93 - New transport connection Transport1[0.0.0.0<00>/192.168.0.150:445,state=0,signingEnforced=false,usage=1]
2019-03-17 00:54:49 DEBUG Transport:568 - Connecting Transport1
2019-03-17 00:54:49 DEBUG SmbTransportImpl:681 - Connecting in state 1 addr 192.168.0.150
2019-03-17 00:54:49 DEBUG SmbTransportImpl:705 - Negotiation response on Transport1 :jcifs.internal.SmbNegotiation@3cebc667
2019-03-17 00:54:49 DEBUG SmbComNegotiateResponse:259 - Signing not-enabled not-required
2019-03-17 00:54:49 DEBUG SmbComNegotiateResponse:295 - Unicode is enabled
2019-03-17 00:54:49 DEBUG SmbTransportImpl:715 - Signature negotiation enforced false (server false) enabled false (server false)
2019-03-17 00:54:49 DEBUG Transport:473 - recv failed
java.io.IOException: end of stream
	at jcifs.util.transport.Transport.loop(Transport.java:448)
	at jcifs.util.transport.Transport.run(Transport.java:769)
	at java.base/java.lang.Thread.run(Thread.java:844)
2019-03-17 00:54:49 DEBUG SmbTransportImpl:394 - Establishing new session SmbSession[credentials=GUEST,targetHost=192.168.0.150,targetDomain=null,uid=0,connectionState=0,usage=1] on Transport1
2019-03-17 00:54:49 WARN  SmbTransportImpl:744 - Disconnecting transport while still in use Transport0[HPF430B907191D<20>/192.168.0.150:445,state=5,signingEnforced=false,usage=2]: [SmbSession[credentials=GUEST,targetHost=hpf430b907191d,targetDomain=null,uid=0,connectionState=2,usage=2]]
2019-03-17 00:54:49 DEBUG SmbTransportImpl:749 - Disconnecting transport Transport0[HPF430B907191D<20>/192.168.0.150:445,state=5,signingEnforced=false,usage=2]
2019-03-17 00:54:49 DEBUG SmbTreeImpl:587 - treeConnect: unc=\\192.168.0.150\IPC$,service=?????
2019-03-17 00:54:49 DEBUG SmbSessionImpl:1114 - Logging off session on Transport0[HPF430B907191D<20>/192.168.0.150:445,state=5,signingEnforced=false,usage=3]
2019-03-17 00:54:49 DEBUG SmbSessionImpl:471 - sessionSetup: GUEST
2019-03-17 00:54:49 WARN  SmbSessionImpl:1122 - Logging off session while still in use SmbSession[credentials=GUEST,targetHost=hpf430b907191d,targetDomain=null,uid=0,connectionState=3,usage=2]:[SmbTree[share=IPC$,service=IPC,tid=0,inDfs=false,inDomainDfs=false,connectionState=2,usage=1]]
2019-03-17 00:54:49 DEBUG SmbSessionImpl:843 - Performing legacy session setup
2019-03-17 00:54:49 DEBUG SmbSessionImpl:1128 - Disconnect tree on logoff
2019-03-17 00:54:49 WARN  SmbTreeImpl:822 - Disconnected tree while still in use SmbTree[share=IPC$,service=IPC,tid=0,inDfs=false,inDomainDfs=false,connectionState=3,usage=1]
2019-03-17 00:54:49 DEBUG SmbTreeImpl:865 - Acquire [jcifs.smb.SmbTreeImpl.acquire(SmbTreeImpl.java:137), jcifs.smb.SmbSessionImpl.getSmbTree(SmbSessionImpl.java:268), jcifs.smb.SmbSessionImpl.getSmbTree(SmbSessionImpl.java:75), jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:562), jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:484), jcifs.smb.SmbEnumerationUtil.doShareEnum(SmbEnumerationUtil.java:149), jcifs.smb.SmbEnumerationUtil.doEnum(SmbEnumerationUtil.java:222), jcifs.smb.SmbEnumerationUtil.listFiles(SmbEnumerationUtil.java:283), jcifs.smb.SmbFile.listFiles(SmbFile.java:1192), smbcli.main(smbcli.java:141)]
2019-03-17 00:54:49 DEBUG SmbTreeImpl:865 - Acquire [jcifs.smb.SmbTreeImpl.acquire(SmbTreeImpl.java:137), jcifs.smb.SmbTreeConnection.connectTree(SmbTreeConnection.java:610), jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:563), jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:484), jcifs.smb.SmbEnumerationUtil.doShareEnum(SmbEnumerationUtil.java:149), jcifs.smb.SmbEnumerationUtil.doEnum(SmbEnumerationUtil.java:222), jcifs.smb.SmbEnumerationUtil.listFiles(SmbEnumerationUtil.java:283), jcifs.smb.SmbFile.listFiles(SmbFile.java:1192), smbcli.main(smbcli.java:141)]
2019-03-17 00:54:49 DEBUG SmbTreeImpl:865 - Acquire [jcifs.smb.SmbTreeImpl.acquire(SmbTreeImpl.java:137), jcifs.smb.SmbTreeConnection.switchTree(SmbTreeConnection.java:145), jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:570), jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:484), jcifs.smb.SmbEnumerationUtil.doShareEnum(SmbEnumerationUtil.java:149), jcifs.smb.SmbEnumerationUtil.doEnum(SmbEnumerationUtil.java:222), jcifs.smb.SmbEnumerationUtil.listFiles(SmbEnumerationUtil.java:283), jcifs.smb.SmbFile.listFiles(SmbFile.java:1192), smbcli.main(smbcli.java:141)]
2019-03-17 00:54:49 WARN  SmbSessionImpl:1132 - Failed to disconnect tree SmbTree[share=IPC$,service=IPC,tid=0,inDfs=false,inDomainDfs=false,connectionState=3,usage=1]
jcifs.RuntimeCIFSException: Disconnected tree while still in use
	at jcifs.smb.SmbTreeImpl.treeDisconnect(SmbTreeImpl.java:826)
	at jcifs.smb.SmbSessionImpl.logoff(SmbSessionImpl.java:1129)
	at jcifs.smb.SmbTransportImpl.doDisconnect(SmbTransportImpl.java:760)
	at jcifs.util.transport.Transport.disconnect(Transport.java:693)
	at jcifs.util.transport.Transport.loop(Transport.java:478)
	at jcifs.util.transport.Transport.run(Transport.java:769)
	at java.base/java.lang.Thread.run(Thread.java:844)
2019-03-17 00:54:49 DEBUG SmbTransportPoolImpl:258 - Removing transport connection Transport0[HPF430B907191D<20>/192.168.0.150:445,state=5,signingEnforced=false,usage=2] (2050059835)
2019-03-17 00:54:49 DEBUG Transport:484 - Disconnected
2019-03-17 00:54:49 DEBUG Transport:493 - Notified clients
2019-03-17 00:54:49 DEBUG SmbTreeImpl:692 - Secure negotiation does not apply
2019-03-17 00:54:49 DEBUG SmbTreeConnection:142 - Switching tree
2019-03-17 00:54:49 DEBUG SmbTreeConnection:144 - Acquired tree on switch SmbTree[share=IPC$,service=IPC,tid=0,inDfs=false,inDomainDfs=false,connectionState=2,usage=2]
2019-03-17 00:54:49 DEBUG SmbTreeConnection:501 - Tree is SmbTree[share=IPC$,service=IPC,tid=0,inDfs=false,inDomainDfs=false,connectionState=2,usage=2]
2019-03-17 00:54:49 DEBUG SmbTreeConnection:501 - Tree is SmbTree[share=IPC$,service=IPC,tid=0,inDfs=false,inDomainDfs=false,connectionState=2,usage=2]
2019-03-17 00:54:49 DEBUG SmbTreeConnection:501 - Tree is SmbTree[share=IPC$,service=IPC,tid=0,inDfs=false,inDomainDfs=false,connectionState=2,usage=2]
2019-03-17 00:54:49 DEBUG SmbFile:643 - openUnshared: \srvsvc flags: 19f0023 access: 20003 attrs: 80 options: 0
2019-03-17 00:54:49 DEBUG SmbTreeConnection:501 - Tree is SmbTree[share=IPC$,service=IPC,tid=0,inDfs=false,inDomainDfs=false,connectionState=2,usage=2]
2019-03-17 00:54:49 DEBUG SmbTreeConnection:321 - Not retrying
jcifs.smb.SmbException: Tree id is 0
	at jcifs.smb.SmbTreeImpl.send(SmbTreeImpl.java:440)
	at jcifs.smb.SmbTreeConnection.send0(SmbTreeConnection.java:399)
	at jcifs.smb.SmbTreeConnection.send(SmbTreeConnection.java:314)
	at jcifs.smb.SmbTreeConnection.send(SmbTreeConnection.java:294)
	at jcifs.smb.SmbTreeHandleImpl.send(SmbTreeHandleImpl.java:130)
	at jcifs.smb.SmbFile.openUnshared(SmbFile.java:675)
	at jcifs.smb.SmbFile.openUnshared(SmbFile.java:634)
	at jcifs.smb.SmbPipeHandleImpl.ensureOpen(SmbPipeHandleImpl.java:179)
	at jcifs.smb.SmbPipeHandleImpl.sendrecv(SmbPipeHandleImpl.java:250)
	at jcifs.dcerpc.DcerpcPipeHandle.doSendReceiveFragment(DcerpcPipeHandle.java:113)
	at jcifs.dcerpc.DcerpcHandle.sendrecv(DcerpcHandle.java:243)
	at jcifs.dcerpc.DcerpcHandle.bind(DcerpcHandle.java:216)
	at jcifs.dcerpc.DcerpcHandle.sendrecv(DcerpcHandle.java:234)
	at jcifs.smb.SmbEnumerationUtil.doMsrpcShareEnum(SmbEnumerationUtil.java:92)
	at jcifs.smb.SmbEnumerationUtil.doShareEnum(SmbEnumerationUtil.java:153)
	at jcifs.smb.SmbEnumerationUtil.doEnum(SmbEnumerationUtil.java:222)
	at jcifs.smb.SmbEnumerationUtil.listFiles(SmbEnumerationUtil.java:283)
	at jcifs.smb.SmbFile.listFiles(SmbFile.java:1192)
	at smbcli.main(smbcli.java:141)
2019-03-17 00:54:49 DEBUG SmbTreeConnection:217 - Tree connection no longer in use, release tree SmbTree[share=IPC$,service=IPC,tid=0,inDfs=false,inDomainDfs=false,connectionState=2,usage=2]
2019-03-17 00:54:49 DEBUG SmbTreeImpl:217 - Usage dropped to zero, release session
2019-03-17 00:54:49 DEBUG SmbSessionImpl:228 - Usage dropped to zero, release connection Transport1[0.0.0.0<00>/192.168.0.150:445,state=3,signingEnforced=false,usage=1]
2019-03-17 00:54:49 DEBUG SmbEnumerationUtil:159 - doMsrpcShareEnum failed
jcifs.smb.SmbException: Tree id is 0
	at jcifs.smb.SmbTreeImpl.send(SmbTreeImpl.java:440)
	at jcifs.smb.SmbTreeConnection.send0(SmbTreeConnection.java:399)
	at jcifs.smb.SmbTreeConnection.send(SmbTreeConnection.java:314)
	at jcifs.smb.SmbTreeConnection.send(SmbTreeConnection.java:294)
	at jcifs.smb.SmbTreeHandleImpl.send(SmbTreeHandleImpl.java:130)
	at jcifs.smb.SmbFile.openUnshared(SmbFile.java:675)
	at jcifs.smb.SmbFile.openUnshared(SmbFile.java:634)
	at jcifs.smb.SmbPipeHandleImpl.ensureOpen(SmbPipeHandleImpl.java:179)
	at jcifs.smb.SmbPipeHandleImpl.sendrecv(SmbPipeHandleImpl.java:250)
	at jcifs.dcerpc.DcerpcPipeHandle.doSendReceiveFragment(DcerpcPipeHandle.java:113)
	at jcifs.dcerpc.DcerpcHandle.sendrecv(DcerpcHandle.java:243)
	at jcifs.dcerpc.DcerpcHandle.bind(DcerpcHandle.java:216)
	at jcifs.dcerpc.DcerpcHandle.sendrecv(DcerpcHandle.java:234)
	at jcifs.smb.SmbEnumerationUtil.doMsrpcShareEnum(SmbEnumerationUtil.java:92)
	at jcifs.smb.SmbEnumerationUtil.doShareEnum(SmbEnumerationUtil.java:153)
	at jcifs.smb.SmbEnumerationUtil.doEnum(SmbEnumerationUtil.java:222)
	at jcifs.smb.SmbEnumerationUtil.listFiles(SmbEnumerationUtil.java:283)
	at jcifs.smb.SmbFile.listFiles(SmbFile.java:1192)
	at smbcli.main(smbcli.java:141)
2019-03-17 00:54:49 DEBUG SmbTreeConnection:501 - Tree is SmbTree[share=IPC$,service=IPC,tid=0,inDfs=false,inDomainDfs=false,connectionState=3,usage=2]
2019-03-17 00:54:49 DEBUG SmbTreeConnection:217 - Tree connection no longer in use, release tree SmbTree[share=IPC$,service=IPC,tid=0,inDfs=false,inDomainDfs=false,connectionState=3,usage=2]
2019-03-17 00:54:49 DEBUG SmbTreeImpl:217 - Usage dropped to zero, release session
2019-03-17 00:54:49 DEBUG SmbSessionImpl:228 - Usage dropped to zero, release connection Transport0[HPF430B907191D<20>/192.168.0.150:445,state=6,signingEnforced=false,usage=1]
Exception in thread "main" java.lang.NullPointerException
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:504)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:484)
	at jcifs.smb.SmbTreeConnection.connect(SmbTreeConnection.java:460)
	at jcifs.smb.SmbTreeConnection.connectWrapException(SmbTreeConnection.java:421)
	at jcifs.smb.SmbTreeConnection.resolveDfs0(SmbTreeConnection.java:684)
	at jcifs.smb.SmbTreeConnection.ensureDFSResolved(SmbTreeConnection.java:653)
	at jcifs.smb.SmbTreeConnection.send0(SmbTreeConnection.java:393)
	at jcifs.smb.SmbTreeConnection.send(SmbTreeConnection.java:314)
	at jcifs.smb.SmbTreeConnection.send(SmbTreeConnection.java:294)
	at jcifs.smb.SmbTreeHandleImpl.send(SmbTreeHandleImpl.java:130)
	at jcifs.smb.SmbEnumerationUtil.doNetShareEnum(SmbEnumerationUtil.java:104)
	at jcifs.smb.SmbEnumerationUtil.doShareEnum(SmbEnumerationUtil.java:160)
	at jcifs.smb.SmbEnumerationUtil.doEnum(SmbEnumerationUtil.java:222)
	at jcifs.smb.SmbEnumerationUtil.listFiles(SmbEnumerationUtil.java:283)
	at jcifs.smb.SmbFile.listFiles(SmbFile.java:1192)
	at smbcli.main(smbcli.java:141)
2019-03-17 00:54:49 DEBUG SmbTransportPoolImpl:277 - Closing pool
2019-03-17 00:54:49 DEBUG SmbTransportPoolImpl:277 - Closing pool
2019-03-17 00:54:49 DEBUG SmbTransportImpl:749 - Disconnecting transport Transport1[0.0.0.0<00>/192.168.0.150:445,state=5,signingEnforced=false,usage=0]
2019-03-17 00:54:49 DEBUG SmbSessionImpl:1114 - Logging off session on Transport1[0.0.0.0<00>/192.168.0.150:445,state=5,signingEnforced=false,usage=1]
2019-03-17 00:54:49 DEBUG SmbSessionImpl:1128 - Disconnect tree on logoff
2019-03-17 00:54:49 DEBUG SmbSessionImpl:183 - Reacquire transport
2019-03-17 00:54:49 DEBUG SmbSessionImpl:228 - Usage dropped to zero, release connection Transport1[0.0.0.0<00>/192.168.0.150:445,state=5,signingEnforced=false,usage=2]
2019-03-17 00:54:49 DEBUG Transport:560 - Trying to connect a disconnected transport
2019-03-17 00:54:49 DEBUG SmbTransportPoolImpl:258 - Removing transport connection Transport1[0.0.0.0<00>/192.168.0.150:445,state=5,signingEnforced=false,usage=0] (24777135)
2019-03-17 00:54:49 DEBUG Transport:484 - Disconnected
```

**Comment by mbechler** [comment]
This is a "fun" one: tid=0 has been used as a invalid/magic value in the original library, but looking at the specification this is a completely valid one.

**Comment by courville** [comment]
Oh, ok. Note however that with the jcifs-1.3.19 original from samba.org it was working (listing nothing) on nova video player android app (if it can help knowing this fact).

**Comment by mbechler** [comment]
Yes, on second inspection the hard check was probably added by me. But this should be fixed now.

**Comment by courville** [comment]
It works now thanks but still have some strange CIFSException:
```
2019-03-17 11:30:28 ERROR PropertyConfiguration:702 - UniAddress resolveOrder specifies WINS however  WINS server has not been configured
2019-03-17 11:30:28 ERROR PropertyConfiguration:702 - UniAddress resolveOrder specifies WINS however  WINS server has not been configured
2019-03-17 11:30:28 INFO  smbcli:100 - this is a information log message
2019-03-17 11:30:28 WARN  smbcli:101 - this is a warning log message
2019-03-17 11:30:28 INFO  smbcli:103 - This is my first log4j's statement
Enabling SMB2

smbFile is a server
2019-03-17 11:30:28 DEBUG SmbTransportPoolImpl:93 - New transport connection Transport0[HPF430B907191D<20>/192.168.0.150:445,state=0,signingEnforced=false,usage=1]
2019-03-17 11:30:28 DEBUG Transport:568 - Connecting Transport0
2019-03-17 11:30:28 DEBUG SmbTransportImpl:681 - Connecting in state 1 addr 192.168.0.150
2019-03-17 11:30:28 DEBUG SmbTransportImpl:705 - Negotiation response on Transport0 :jcifs.internal.SmbNegotiation@5e984243
2019-03-17 11:30:28 DEBUG SmbComNegotiateResponse:259 - Signing not-enabled not-required
2019-03-17 11:30:28 DEBUG SmbComNegotiateResponse:295 - Unicode is enabled
2019-03-17 11:30:28 DEBUG SmbTransportImpl:715 - Signature negotiation enforced false (server false) enabled false (server false)
2019-03-17 11:30:28 DEBUG SmbTransportImpl:394 - Establishing new session SmbSession[credentials=GUEST,targetHost=hpf430b907191d,targetDomain=null,uid=0,connectionState=0,usage=1] on Transport0
2019-03-17 11:30:28 DEBUG SmbTreeImpl:584 - treeConnect: unc=\\hpf430b907191d\IPC$,service=?????
2019-03-17 11:30:28 DEBUG SmbSessionImpl:471 - sessionSetup: GUEST
2019-03-17 11:30:28 DEBUG SmbSessionImpl:843 - Performing legacy session setup
2019-03-17 11:30:28 DEBUG SmbTreeImpl:689 - Secure negotiation does not apply
2019-03-17 11:30:28 DEBUG SmbTreeConnection:143 - Switching tree
2019-03-17 11:30:28 DEBUG SmbTreeConnection:145 - Acquired tree on switch SmbTree[share=IPC$,service=IPC,tid=0,inDfs=false,inDomainDfs=false,connectionState=2,usage=2]
2019-03-17 11:30:28 DEBUG SmbResourceLocatorImpl:392 - Share is IPC IPC$
2019-03-17 11:30:28 DEBUG SmbTransportPoolImpl:93 - New transport connection Transport1[0.0.0.0<00>/192.168.0.150:445,state=0,signingEnforced=false,usage=1]
2019-03-17 11:30:28 DEBUG Transport:568 - Connecting Transport1
2019-03-17 11:30:28 DEBUG SmbTransportImpl:681 - Connecting in state 1 addr 192.168.0.150
2019-03-17 11:30:28 DEBUG Transport:473 - recv failed
java.io.IOException: end of stream
	at jcifs.util.transport.Transport.loop(Transport.java:448)
	at jcifs.util.transport.Transport.run(Transport.java:769)
	at java.base/java.lang.Thread.run(Thread.java:844)
2019-03-17 11:30:28 DEBUG SmbTransportImpl:705 - Negotiation response on Transport1 :jcifs.internal.SmbNegotiation@51df1b4f
2019-03-17 11:30:28 WARN  SmbTransportImpl:744 - Disconnecting transport while still in use Transport0[HPF430B907191D<20>/192.168.0.150:445,state=5,signingEnforced=false,usage=2]: [SmbSession[credentials=GUEST,targetHost=hpf430b907191d,targetDomain=null,uid=0,connectionState=2,usage=2]]
2019-03-17 11:30:28 DEBUG SmbTransportImpl:749 - Disconnecting transport Transport0[HPF430B907191D<20>/192.168.0.150:445,state=5,signingEnforced=false,usage=2]
2019-03-17 11:30:28 DEBUG SmbComNegotiateResponse:259 - Signing not-enabled not-required
2019-03-17 11:30:28 DEBUG SmbSessionImpl:1114 - Logging off session on Transport0[HPF430B907191D<20>/192.168.0.150:445,state=5,signingEnforced=false,usage=3]
2019-03-17 11:30:28 DEBUG SmbComNegotiateResponse:295 - Unicode is enabled
2019-03-17 11:30:28 DEBUG SmbTransportImpl:715 - Signature negotiation enforced false (server false) enabled false (server false)
2019-03-17 11:30:28 WARN  SmbSessionImpl:1122 - Logging off session while still in use SmbSession[credentials=GUEST,targetHost=hpf430b907191d,targetDomain=null,uid=0,connectionState=3,usage=2]:[SmbTree[share=IPC$,service=IPC,tid=0,inDfs=false,inDomainDfs=false,connectionState=2,usage=1]]
2019-03-17 11:30:28 DEBUG SmbSessionImpl:1128 - Disconnect tree on logoff
2019-03-17 11:30:28 DEBUG SmbTransportImpl:394 - Establishing new session SmbSession[credentials=GUEST,targetHost=192.168.0.150,targetDomain=null,uid=0,connectionState=0,usage=1] on Transport1
2019-03-17 11:30:28 WARN  SmbTreeImpl:819 - Disconnected tree while still in use SmbTree[share=IPC$,service=IPC,tid=0,inDfs=false,inDomainDfs=false,connectionState=3,usage=1]
2019-03-17 11:30:28 DEBUG SmbTreeImpl:584 - treeConnect: unc=\\192.168.0.150\IPC$,service=?????
2019-03-17 11:30:28 DEBUG SmbTreeImpl:862 - Acquire [jcifs.smb.SmbTreeImpl.acquire(SmbTreeImpl.java:137), jcifs.smb.SmbSessionImpl.getSmbTree(SmbSessionImpl.java:268), jcifs.smb.SmbSessionImpl.getSmbTree(SmbSessionImpl.java:75), jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:563), jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:485), jcifs.smb.SmbEnumerationUtil.doShareEnum(SmbEnumerationUtil.java:149), jcifs.smb.SmbEnumerationUtil.doEnum(SmbEnumerationUtil.java:222), jcifs.smb.SmbEnumerationUtil.listFiles(SmbEnumerationUtil.java:283), jcifs.smb.SmbFile.listFiles(SmbFile.java:1192), smbcli.main(smbcli.java:142)]
2019-03-17 11:30:28 DEBUG SmbSessionImpl:471 - sessionSetup: GUEST
2019-03-17 11:30:28 DEBUG SmbTreeImpl:862 - Acquire [jcifs.smb.SmbTreeImpl.acquire(SmbTreeImpl.java:137), jcifs.smb.SmbTreeConnection.connectTree(SmbTreeConnection.java:611), jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:564), jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:485), jcifs.smb.SmbEnumerationUtil.doShareEnum(SmbEnumerationUtil.java:149), jcifs.smb.SmbEnumerationUtil.doEnum(SmbEnumerationUtil.java:222), jcifs.smb.SmbEnumerationUtil.listFiles(SmbEnumerationUtil.java:283), jcifs.smb.SmbFile.listFiles(SmbFile.java:1192), smbcli.main(smbcli.java:142)]
2019-03-17 11:30:28 DEBUG SmbTreeImpl:862 - Acquire [jcifs.smb.SmbTreeImpl.acquire(SmbTreeImpl.java:137), jcifs.smb.SmbTreeConnection.switchTree(SmbTreeConnection.java:146), jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:571), jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:485), jcifs.smb.SmbEnumerationUtil.doShareEnum(SmbEnumerationUtil.java:149), jcifs.smb.SmbEnumerationUtil.doEnum(SmbEnumerationUtil.java:222), jcifs.smb.SmbEnumerationUtil.listFiles(SmbEnumerationUtil.java:283), jcifs.smb.SmbFile.listFiles(SmbFile.java:1192), smbcli.main(smbcli.java:142)]
2019-03-17 11:30:28 DEBUG SmbSessionImpl:843 - Performing legacy session setup
2019-03-17 11:30:28 WARN  SmbSessionImpl:1132 - Failed to disconnect tree SmbTree[share=IPC$,service=IPC,tid=0,inDfs=false,inDomainDfs=false,connectionState=3,usage=1]
jcifs.RuntimeCIFSException: Disconnected tree while still in use
	at jcifs.smb.SmbTreeImpl.treeDisconnect(SmbTreeImpl.java:823)
	at jcifs.smb.SmbSessionImpl.logoff(SmbSessionImpl.java:1129)
	at jcifs.smb.SmbTransportImpl.doDisconnect(SmbTransportImpl.java:760)
	at jcifs.util.transport.Transport.disconnect(Transport.java:693)
	at jcifs.util.transport.Transport.loop(Transport.java:478)
	at jcifs.util.transport.Transport.run(Transport.java:769)
	at java.base/java.lang.Thread.run(Thread.java:844)
2019-03-17 11:30:28 DEBUG SmbTransportPoolImpl:258 - Removing transport connection Transport0[HPF430B907191D<20>/192.168.0.150:445,state=5,signingEnforced=false,usage=2] (357223599)
2019-03-17 11:30:28 DEBUG Transport:484 - Disconnected
2019-03-17 11:30:28 DEBUG Transport:493 - Notified clients
2019-03-17 11:30:28 DEBUG SmbTreeImpl:689 - Secure negotiation does not apply
2019-03-17 11:30:28 DEBUG SmbTreeConnection:143 - Switching tree
2019-03-17 11:30:28 DEBUG SmbTreeConnection:145 - Acquired tree on switch SmbTree[share=IPC$,service=IPC,tid=0,inDfs=false,inDomainDfs=false,connectionState=2,usage=2]
2019-03-17 11:30:28 DEBUG SmbFile:643 - openUnshared: \srvsvc flags: 19f0023 access: 20003 attrs: 80 options: 0
2019-03-17 11:30:28 DEBUG SmbTreeConnection:322 - Not retrying
jcifs.smb.SmbUnsupportedOperationException: Operation is not supported with the negotiated capabilities
	at jcifs.smb.SmbTransportImpl.checkStatus(SmbTransportImpl.java:1362)
	at jcifs.smb.SmbTransportImpl.checkStatus(SmbTransportImpl.java:1557)
	at jcifs.smb.SmbTransportImpl.sendrecv(SmbTransportImpl.java:1007)
	at jcifs.smb.SmbTransportImpl.send(SmbTransportImpl.java:1523)
	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:409)
	at jcifs.smb.SmbTreeImpl.send(SmbTreeImpl.java:469)
	at jcifs.smb.SmbTreeConnection.send0(SmbTreeConnection.java:400)
	at jcifs.smb.SmbTreeConnection.send(SmbTreeConnection.java:315)
	at jcifs.smb.SmbTreeConnection.send(SmbTreeConnection.java:295)
	at jcifs.smb.SmbTreeHandleImpl.send(SmbTreeHandleImpl.java:130)
	at jcifs.smb.SmbFile.openUnshared(SmbFile.java:675)
	at jcifs.smb.SmbFile.openUnshared(SmbFile.java:634)
	at jcifs.smb.SmbPipeHandleImpl.ensureOpen(SmbPipeHandleImpl.java:179)
	at jcifs.smb.SmbPipeHandleImpl.sendrecv(SmbPipeHandleImpl.java:250)
	at jcifs.dcerpc.DcerpcPipeHandle.doSendReceiveFragment(DcerpcPipeHandle.java:113)
	at jcifs.dcerpc.DcerpcHandle.sendrecv(DcerpcHandle.java:243)
	at jcifs.dcerpc.DcerpcHandle.bind(DcerpcHandle.java:216)
	at jcifs.dcerpc.DcerpcHandle.sendrecv(DcerpcHandle.java:234)
	at jcifs.smb.SmbEnumerationUtil.doMsrpcShareEnum(SmbEnumerationUtil.java:92)
	at jcifs.smb.SmbEnumerationUtil.doShareEnum(SmbEnumerationUtil.java:153)
	at jcifs.smb.SmbEnumerationUtil.doEnum(SmbEnumerationUtil.java:222)
	at jcifs.smb.SmbEnumerationUtil.listFiles(SmbEnumerationUtil.java:283)
	at jcifs.smb.SmbFile.listFiles(SmbFile.java:1192)
	at smbcli.main(smbcli.java:142)
2019-03-17 11:30:28 DEBUG SmbTreeConnection:218 - Tree connection no longer in use, release tree SmbTree[share=IPC$,service=IPC,tid=0,inDfs=false,inDomainDfs=false,connectionState=2,usage=2]
2019-03-17 11:30:28 DEBUG SmbTreeImpl:217 - Usage dropped to zero, release session
2019-03-17 11:30:28 DEBUG SmbSessionImpl:228 - Usage dropped to zero, release connection Transport1[0.0.0.0<00>/192.168.0.150:445,state=3,signingEnforced=false,usage=1]
2019-03-17 11:30:28 DEBUG SmbEnumerationUtil:159 - doMsrpcShareEnum failed
jcifs.smb.SmbUnsupportedOperationException: Operation is not supported with the negotiated capabilities
	at jcifs.smb.SmbTransportImpl.checkStatus(SmbTransportImpl.java:1362)
	at jcifs.smb.SmbTransportImpl.checkStatus(SmbTransportImpl.java:1557)
	at jcifs.smb.SmbTransportImpl.sendrecv(SmbTransportImpl.java:1007)
	at jcifs.smb.SmbTransportImpl.send(SmbTransportImpl.java:1523)
	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:409)
	at jcifs.smb.SmbTreeImpl.send(SmbTreeImpl.java:469)
	at jcifs.smb.SmbTreeConnection.send0(SmbTreeConnection.java:400)
	at jcifs.smb.SmbTreeConnection.send(SmbTreeConnection.java:315)
	at jcifs.smb.SmbTreeConnection.send(SmbTreeConnection.java:295)
	at jcifs.smb.SmbTreeHandleImpl.send(SmbTreeHandleImpl.java:130)
	at jcifs.smb.SmbFile.openUnshared(SmbFile.java:675)
	at jcifs.smb.SmbFile.openUnshared(SmbFile.java:634)
	at jcifs.smb.SmbPipeHandleImpl.ensureOpen(SmbPipeHandleImpl.java:179)
	at jcifs.smb.SmbPipeHandleImpl.sendrecv(SmbPipeHandleImpl.java:250)
	at jcifs.dcerpc.DcerpcPipeHandle.doSendReceiveFragment(DcerpcPipeHandle.java:113)
	at jcifs.dcerpc.DcerpcHandle.sendrecv(DcerpcHandle.java:243)
	at jcifs.dcerpc.DcerpcHandle.bind(DcerpcHandle.java:216)
	at jcifs.dcerpc.DcerpcHandle.sendrecv(DcerpcHandle.java:234)
	at jcifs.smb.SmbEnumerationUtil.doMsrpcShareEnum(SmbEnumerationUtil.java:92)
	at jcifs.smb.SmbEnumerationUtil.doShareEnum(SmbEnumerationUtil.java:153)
	at jcifs.smb.SmbEnumerationUtil.doEnum(SmbEnumerationUtil.java:222)
	at jcifs.smb.SmbEnumerationUtil.listFiles(SmbEnumerationUtil.java:283)
	at jcifs.smb.SmbFile.listFiles(SmbFile.java:1192)
	at smbcli.main(smbcli.java:142)
2019-03-17 11:30:28 DEBUG SmbTreeConnection:502 - Tree is SmbTree[share=IPC$,service=IPC,tid=0,inDfs=false,inDomainDfs=false,connectionState=3,usage=2]
2019-03-17 11:30:28 DEBUG SmbTransportPoolImpl:93 - New transport connection Transport2[HPF430B907191D<20>/192.168.0.150:445,state=0,signingEnforced=false,usage=1]
2019-03-17 11:30:28 DEBUG Transport:568 - Connecting Transport2
2019-03-17 11:30:28 DEBUG SmbTransportImpl:681 - Connecting in state 1 addr 192.168.0.150
2019-03-17 11:30:28 DEBUG Transport:473 - recv failed
java.io.IOException: end of stream
	at jcifs.util.transport.Transport.loop(Transport.java:448)
	at jcifs.util.transport.Transport.run(Transport.java:769)
	at java.base/java.lang.Thread.run(Thread.java:844)
2019-03-17 11:30:28 DEBUG SmbTransportImpl:749 - Disconnecting transport Transport1[0.0.0.0<00>/192.168.0.150:445,state=5,signingEnforced=false,usage=0]
2019-03-17 11:30:28 DEBUG SmbSessionImpl:1114 - Logging off session on Transport1[0.0.0.0<00>/192.168.0.150:445,state=5,signingEnforced=false,usage=1]
2019-03-17 11:30:28 DEBUG SmbSessionImpl:1128 - Disconnect tree on logoff
2019-03-17 11:30:28 DEBUG SmbSessionImpl:183 - Reacquire transport
2019-03-17 11:30:28 DEBUG SmbSessionImpl:228 - Usage dropped to zero, release connection Transport1[0.0.0.0<00>/192.168.0.150:445,state=5,signingEnforced=false,usage=2]
2019-03-17 11:30:28 DEBUG SmbTransportPoolImpl:258 - Removing transport connection Transport1[0.0.0.0<00>/192.168.0.150:445,state=5,signingEnforced=false,usage=0] (1529311295)
2019-03-17 11:30:28 DEBUG Transport:484 - Disconnected
2019-03-17 11:30:28 DEBUG Transport:493 - Notified clients
2019-03-17 11:30:28 DEBUG SmbTransportImpl:705 - Negotiation response on Transport2 :jcifs.internal.SmbNegotiation@2843dc2a
2019-03-17 11:30:28 DEBUG SmbComNegotiateResponse:259 - Signing not-enabled not-required
2019-03-17 11:30:28 DEBUG SmbComNegotiateResponse:295 - Unicode is enabled
2019-03-17 11:30:28 DEBUG SmbTransportImpl:715 - Signature negotiation enforced false (server false) enabled false (server false)
2019-03-17 11:30:28 DEBUG SmbTransportImpl:394 - Establishing new session SmbSession[credentials=GUEST,targetHost=hpf430b907191d,targetDomain=null,uid=0,connectionState=0,usage=1] on Transport2
2019-03-17 11:30:28 DEBUG SmbTreeImpl:584 - treeConnect: unc=\\hpf430b907191d\IPC$,service=?????
2019-03-17 11:30:28 DEBUG SmbSessionImpl:471 - sessionSetup: GUEST
2019-03-17 11:30:28 DEBUG SmbSessionImpl:843 - Performing legacy session setup
2019-03-17 11:30:28 DEBUG SmbTreeImpl:689 - Secure negotiation does not apply
2019-03-17 11:30:28 DEBUG SmbTreeConnection:143 - Switching tree
2019-03-17 11:30:28 DEBUG SmbTreeConnection:145 - Acquired tree on switch SmbTree[share=IPC$,service=IPC,tid=0,inDfs=false,inDomainDfs=false,connectionState=2,usage=2]
2019-03-17 11:30:28 DEBUG SmbTreeImpl:217 - Usage dropped to zero, release session
2019-03-17 11:30:28 DEBUG SmbSessionImpl:228 - Usage dropped to zero, release connection Transport0[HPF430B907191D<20>/192.168.0.150:445,state=6,signingEnforced=false,usage=1]
2019-03-17 11:30:28 DEBUG SmbTreeConnection:218 - Tree connection no longer in use, release tree SmbTree[share=IPC$,service=IPC,tid=0,inDfs=false,inDomainDfs=false,connectionState=2,usage=2]
2019-03-17 11:30:28 DEBUG SmbTreeImpl:217 - Usage dropped to zero, release session
2019-03-17 11:30:28 DEBUG SmbSessionImpl:228 - Usage dropped to zero, release connection Transport2[HPF430B907191D<20>/192.168.0.150:445,state=3,signingEnforced=false,usage=1]
2019-03-17 11:30:28 DEBUG SmbSessionImpl:183 - Reacquire transport
2019-03-17 11:30:28 DEBUG SmbTreeImpl:175 - Reacquire session
2019-03-17 11:30:28 DEBUG SmbTreeConnection:143 - Switching tree
2019-03-17 11:30:28 DEBUG SmbTreeConnection:145 - Acquired tree on switch SmbTree[share=IPC$,service=IPC,tid=0,inDfs=false,inDomainDfs=false,connectionState=2,usage=2]
2019-03-17 11:30:28 DEBUG SmbFile:751 - queryPath: \
2019-03-17 11:30:28 DEBUG SmbTreeConnection:322 - Not retrying
jcifs.smb.SmbException: Invalid operation for IPC service: Trans2QueryPathInformation[command=SMB_COM_TRANSACTION2,received=false,errorCode=0,flags=0x0018,flags2=0x0000,signSeq=0,tid=0,pid=38321,uid=0,mid=0,wordCount=0,byteCount=0,totalParameterCount=0,totalDataCount=0,maxParameterCount=2,maxDataCount=40,maxSetupCount=0,flags=0x00,timeout=0,parameterCount=0,parameterOffset=0,parameterDisplacement=0,dataCount=0,dataOffset=0,dataDisplacement=0,setupCount=1,pad=0,pad1=0,informationLevel=0x004,filename=\]
	at jcifs.smb.SmbTreeImpl.checkRequest(SmbTreeImpl.java:516)
	at jcifs.smb.SmbTreeImpl.send(SmbTreeImpl.java:449)
	at jcifs.smb.SmbTreeConnection.send0(SmbTreeConnection.java:400)
	at jcifs.smb.SmbTreeConnection.send(SmbTreeConnection.java:315)
	at jcifs.smb.SmbTreeConnection.send(SmbTreeConnection.java:295)
	at jcifs.smb.SmbTreeHandleImpl.send(SmbTreeHandleImpl.java:130)
	at jcifs.smb.SmbFile.queryPath(SmbFile.java:770)
	at jcifs.smb.SmbFile.exists(SmbFile.java:844)
	at smbcli.main(smbcli.java:161)
2019-03-17 11:30:28 DEBUG SmbTreeConnection:218 - Tree connection no longer in use, release tree SmbTree[share=IPC$,service=IPC,tid=0,inDfs=false,inDomainDfs=false,connectionState=2,usage=2]
2019-03-17 11:30:28 DEBUG SmbTreeImpl:217 - Usage dropped to zero, release session
2019-03-17 11:30:28 DEBUG SmbSessionImpl:228 - Usage dropped to zero, release connection Transport2[HPF430B907191D<20>/192.168.0.150:445,state=3,signingEnforced=false,usage=1]
smb://HPF430B907191D/IPC$/ exists but not accessible
2019-03-17 11:30:28 DEBUG SmbTransportPoolImpl:277 - Closing pool
2019-03-17 11:30:28 DEBUG SmbTransportImpl:749 - Disconnecting transport Transport2[HPF430B907191D<20>/192.168.0.150:445,state=5,signingEnforced=false,usage=0]
2019-03-17 11:30:28 DEBUG SmbSessionImpl:1114 - Logging off session on Transport2[HPF430B907191D<20>/192.168.0.150:445,state=5,signingEnforced=false,usage=1]
2019-03-17 11:30:28 DEBUG SmbTransportPoolImpl:277 - Closing pool
2019-03-17 11:30:28 DEBUG SmbSessionImpl:1128 - Disconnect tree on logoff
2019-03-17 11:30:28 DEBUG SmbSessionImpl:183 - Reacquire transport
2019-03-17 11:30:28 DEBUG Transport:560 - Trying to connect a disconnected transport
2019-03-17 11:30:28 DEBUG SmbSessionImpl:228 - Usage dropped to zero, release connection Transport2[HPF430B907191D<20>/192.168.0.150:445,state=5,signingEnforced=false,usage=2]
2019-03-17 11:30:28 DEBUG Transport:560 - Trying to connect a disconnected transport
2019-03-17 11:30:28 DEBUG SmbTransportPoolImpl:258 - Removing transport connection Transport2[HPF430B907191D<20>/192.168.0.150:445,state=5,signingEnforced=false,usage=0] (230718955)
2019-03-17 11:30:28 DEBUG Transport:484 - Disconnected
```
I can provide pcap if need be.

**Comment by mbechler** [comment]
pcap would ge good. The disconnect in a strange state appears to be caused by 
```
2019-03-17 11:30:28 DEBUG Transport:473 - recv failed
java.io.IOException: end of stream
```
which could be the server closing the connection, it's also somewhat strange that new connections are made all the time.

**Comment by courville** [comment]
Here it is:  [hpprinter-smbexception-browsing3.pcap.zip](https://github.com/AgNO3/jcifs-ng/files/2975032/hpprinter-smbexception-browsing3.pcap.zip)

**Comment by mbechler** [comment]
It looks like the server is closing the existing connection as soon as a second connection attempt is made. While unexpected, the interesting question in this case is why the original connection is not being reused, I'll try to replicate that.

**Comment by courville** [comment]
Thank you!

**Comment by courville** [comment]
A comment out of scope of this thread to let you know that I have incorporated your latest 2.1.3 snapshot into Android Nova Video Player https://github.com/nova-video-player/aos-FileCoreLibrary/commit/839e524244a9867681738ebbdc7e46c3a2ca906f and it seems to work like a charm. I will make a public beta (~400 users) for testing later today and will let people test it and report on reddit community  https://www.reddit.com/r/NovaVideoPlayer
Thank you again for your hard work and reactivity on the issues that I have reported.

**Comment by courville** [comment]
And while I am at it for out of scope, I have gathered in the following gist and comments my little memo for noobs to get captures and trace logs with my test program to help others https://gist.github.com/courville/a0e6fe1ce2f31c9adc52191216eed3e0

**Comment by mbechler** [comment]
This should fix the connection reuse issue. With only one connection (I guess this is a server imposed limit of some kind) this hopefully prevents the disconnect and thereby the warning.

**Comment by courville** [comment]
I confirm the fix.
Thanks: issue closed.
